#-------------------------------
# General Site Settings

title: Muhammet Koç
logo: 
author: Muhammet Koç
description: Kişisel web sitesi
email: muhammetkoc@tutamail.com
phone: sadece email
address: İzmir / Türkiye
copyright: Copyright &copy; 2021 Redesigned by [mhmmtkc](https://mhmmtkc.github.io/about) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: Hakkımda, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Projeler, link: '/portfolio'}
- {name: İletişim, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: <font size="8">Bir şeye ait her şeyi öğrenin, <br> her şeye dair bir şeyler bilin.</font> <br> <font size="5">-H. Van Dyke</font>

social:
#- {icon: "ti-facebook", link: "#"}
- {icon: "ti-twitter", link: "https://twitter.com/mhmmtkc_"}
- {icon: "ti-twitter", link: "https://twitter.com/mhmmtkc_"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCU_zl2kL5U73QVT_TYA2G8A"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCU_zl2kL5U73QVT_TYA2G8A"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Gebze Teknik Üniversitesi elektronik mühendisliği öğrencisiyim. Yazılım ile uğraşmayı ve kodlamayı seviyorum. Kod yazmak, algoritma oluşturmak beni mutlu ediyor. 

blurb-btn-link: '/about'
blurb-btn-name: Daha fazla


# About Page

# Work Process Section
work-process:
  - title : "Araştırma ve planlama"
    icon : "assets/images/icons/plan.png"
    content : "Başlamadan önce iş sürecinde gerekli bilgileri araştırmak iş planını kolaylaştırır ve bir hatayla karşılaşıldığında çözüm bulmayı kolaylaştırır."
    
  - title : "Dizayn ve Geliştirme"
    icon : "assets/images/icons/design.png"
    content : "Planımız hazırsa artık projemize hayat vermeye başlarız. Özenle en iyi şekilde sonuçlandırmaya çalışırız."
    
  - title : "Teslimat ve Kullanım"
    icon : "assets/images/icons/print.png"
    content : "Kullanıma hazır hale geldiğinde amacına uygun şekilde kullanıma sunulur."


#-------------------------------
# Skills Section

skills-title: Beceriler
skills:
- {name: C++, color: '#fdb157', value: '40%'}
- {name: C, color: '#9473e6', value: '30%'}
- {name: Python, color: '#bdecf6', value: '10%'}
- {name: Algoritma, color: '#ffbcaa', value: '20%'}


#-------------------------------
# Exprerience Section

experience-title: Deneyim
experience:
- {name: Junior Devoloper, icon: 'icon-1.png', date: '2020-2021', organization: 'Uzaktan eğitim boyunca kendi evimde kendi kendime'}


#-------------------------------
# Education Section

education-title: Eğitim
education:
- {name: Elektronik Mühendisliği, date: '2024', organization: 'Gebze Teknik Üniversitesi'}
- {name: Lise, date: '2019', organization: 'Ödemiş Ticaret Odası Anadolu Lisesi'}

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"


# Project Page
portfolio-label:
- {
    title : "C++ programmning",
    type : "Consol"
  }
- {
    title : "C programming",
    type : "Consol"
  }
- {
    title : "Python programming",
    type : "Consol"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    title : "Atanmadı"
    url: "#"
    portfolio-type:
     - type: "consol"
#     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "https://github.com/mhmmtkc/CalorieTracker"
    title : "Calorie tracker"
    portfolio-type:
      - type: "consol"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    title : "Atanmadı"
    portfolio-type:
      - type: "consol"
      
      
#-------------------------------
# Contact Section

contact-title: İletişim Bilgisi
contact-email: muhammetkoc@tutamail.com
